Tue 28 Nov 12:00:01 +08 2017
Processing Kayak Activities...
Processing Bedok Reservoir
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 346, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 356, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/packages/ssl_match_hostname/_implementation.py", line 150, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
urllib3.packages.ssl_match_hostname._implementation.CertificateError: hostname 'one.pa.gov.sg' doesn't match either of 'onepa.sg', 'api.onepa.sg', 'www.onepa.sg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='one.pa.gov.sg', port=443): Max retries exceeded with url: /CRMSPortal/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=action&wlpCRMSPortal_1_action=CMFCategoryActivitySelection&_pageLabel=CRMSPortal_page_1 (Caused by SSLError(CertificateError("hostname 'one.pa.gov.sg' doesn't match either of 'onepa.sg', 'api.onepa.sg', 'www.onepa.sg'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paddlesg/Paddle-SG_Scripts/GetAllActivities.py", line 10, in <module>
    allOutletActivityList += processOutletActivities ("Bedok Reservoir", url, "1395630", operator)
  File "/home/paddlesg/Paddle-SG_Scripts/GetPAOutletActivities.py", line 134, in processOutletActivities
    outletActivityList = getOutletActivityListing(url, outletId, operator)
  File "/home/paddlesg/Paddle-SG_Scripts/GetPAOutletActivities.py", line 13, in getOutletActivityListing
    urlResponseObj = requests.post(url, data=payload, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='one.pa.gov.sg', port=443): Max retries exceeded with url: /CRMSPortal/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=action&wlpCRMSPortal_1_action=CMFCategoryActivitySelection&_pageLabel=CRMSPortal_page_1 (Caused by SSLError(CertificateError("hostname 'one.pa.gov.sg' doesn't match either of 'onepa.sg', 'api.onepa.sg', 'www.onepa.sg'",),))
Processing Kayak Courses...
Getting Operator Course Dates
Processing One Star Courses
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 346, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 356, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/packages/ssl_match_hostname/_implementation.py", line 150, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
urllib3.packages.ssl_match_hostname._implementation.CertificateError: hostname 'one.pa.gov.sg' doesn't match either of 'onepa.sg', 'api.onepa.sg', 'www.onepa.sg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='one.pa.gov.sg', port=443): Max retries exceeded with url: /CRMSPortal/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFShowClasses&_pageLabel=CRMSPortal_page_1&actionIndex=searchClassList&idProduct=727686 (Caused by SSLError(CertificateError("hostname 'one.pa.gov.sg' doesn't match either of 'onepa.sg', 'api.onepa.sg', 'www.onepa.sg'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paddlesg/Paddle-SG_Scripts/GetAllCourses.py", line 8, in <module>
    processCourses("One Star Courses", "https://one.pa.gov.sg/CRMSPortal/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFShowClasses&_pageLabel=CRMSPortal_page_1&actionIndex=searchClassList&idProduct=727686", "PA", "out-onestar.txt")
  File "/home/paddlesg/Paddle-SG_Scripts/GetPACourses.py", line 166, in processCourses
    listOfAllCourses = getCourseListing(url, operator)
  File "/home/paddlesg/Paddle-SG_Scripts/GetPACourses.py", line 11, in getCourseListing
    urlResponseObj = requests.get(url)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='one.pa.gov.sg', port=443): Max retries exceeded with url: /CRMSPortal/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFShowClasses&_pageLabel=CRMSPortal_page_1&actionIndex=searchClassList&idProduct=727686 (Caused by SSLError(CertificateError("hostname 'one.pa.gov.sg' doesn't match either of 'onepa.sg', 'api.onepa.sg', 'www.onepa.sg'",),))
Producing webpages...
Finished
Tue 28 Nov 12:00:15 +08 2017
